name: website

# build the documentation new commits on main and PRs
on: [push, pull_request]

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      # Install all dependencies (including pdoc3)
      - run: |
          sudo apt-get update -y 
          sudo apt-get install -y python3-poetry
          poetry install --with docs --no-root
      # Build documentation with pdoc3.
      - run: pdoc3 -o docs/ --config='docformat="google"' --force ./openrelik_worker_common

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4